'use client';

import { Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import AdminShell from '@/components/admin/AdminShell'; import ProductDrawer from '@/components/admin/ProductDrawer'; import { Icon } from '@/components/admin/Icons'; import { Confirm, Empty, ErrorState, Skeleton, StatusBadge, Toast } from '@/components/admin/UI';
import { adminFetch } from '@/lib/admin/client'; import { money, Paged, Product } from '@/lib/admin/types';
import { isProductSetupDraft } from '@/lib/productSetup';

function ProductsContent(){
 const params=useSearchParams(); const [type,setType]=useState<'MOBILE'|'MERCHANDISE'>('MERCHANDISE'); const [page,setPage]=useState(1); const [query,setQuery]=useState(''); const [stockFilter,setStockFilter]=useState<'all'|'out'>('all'); const [data,setData]=useState<Paged<Product>|null>(null); const [error,setError]=useState(''); const [editor,setEditor]=useState<Product|null|undefined>(params.get('create')==='1'?null:undefined); const [deleteTarget,setDeleteTarget]=useState<Product|null>(null); const [busy,setBusy]=useState(false); const [toast,setToast]=useState<{message:string;kind:'success'|'error'}|null>(null);
 const load=useCallback(async()=>{setError('');try{setData(await adminFetch<Paged<Product>>(`products?type=${type}&page=${page}&limit=20`));}catch(e){setError(e instanceof Error?e.message:'Unable to load products.')}},[type,page]); useEffect(()=>{load()},[load]);
 const rows=useMemo(()=>data?.data.filter(p=>(stockFilter==='all'||(p.productVariants||[]).reduce((sum,v)=>sum+Number(v.inventory||0),0)===0)&&(!query||`${p.title} ${p.slug} ${p.id}`.toLowerCase().includes(query.toLowerCase())))||[],[data,query,stockFilter]);
 async function remove(){if(!deleteTarget)return;setBusy(true);try{await adminFetch(`products/${deleteTarget.id}/soft-delete`,{method:'DELETE'});setToast({message:'Product soft-deleted.',kind:'success'});setDeleteTarget(null);await load();}catch(e){setToast({message:e instanceof Error?e.message:'Delete failed.',kind:'error'})}finally{setBusy(false)}}
 const flash=(message:string,kind:'success'|'error'='success')=>{setToast({message,kind});if(kind==='success')load()};
 return <AdminShell title="Products" eyebrow="Catalogue"><div className="adm-page-head"><div><h1>Product catalogue</h1><p>Manage details, media, options, variants and inventory.</p></div><button className="adm-button" onClick={()=>setEditor(null)}><Icon name="plus"/><span>New product</span></button></div><div className="adm-toolbar"><div className="adm-tabs"><button className={type==='MOBILE'?'active':''} onClick={()=>{setType('MOBILE');setPage(1)}}>Mobile</button><button className={type==='MERCHANDISE'?'active':''} onClick={()=>{setType('MERCHANDISE');setPage(1)}}>Merchandise</button></div><label className="adm-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, slug or ID…"/></label><select aria-label="Stock filter" value={stockFilter} onChange={e=>setStockFilter(e.target.value as 'all'|'out')}><option value="all">All stock</option><option value="out">Out of stock</option></select></div>
 <section className="adm-panel">{error?<ErrorState message={error} retry={load}/>:!data?<Skeleton/>:!rows.length?<Empty title="No products found" message="Try another search or create a new product." action={<button className="adm-button" onClick={()=>setEditor(null)}>Create product</button>}/>:<><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Product</th><th>Price</th><th>Variants</th><th>Inventory</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(product=>{const stock=(product.productVariants||[]).reduce((sum,v)=>sum+Number(v.inventory||0),0);return <tr key={product.id}><td><div className="adm-product-cell">{product.images?.[0]?<img className="adm-thumb" src={product.images[0].url} alt=""/>:<span className="adm-thumb"/>}<div><strong>{product.title}</strong><small>#{product.id} · {product.slug}</small></div></div></td><td data-label="Price">{money(product.price)}</td><td data-label="Variants">{product.productVariants?.length||0}</td><td data-label="Inventory">{stock}</td><td data-label="Status"><StatusBadge status={product.deletedAt?'DELETED':isProductSetupDraft(product)?'DRAFT':stock===0?'OUT':'ACTIVE'}/></td><td><div className="adm-actions"><button className="adm-icon-btn" title={isProductSetupDraft(product)?'Continue setup':'Edit'} onClick={()=>setEditor(product)}><Icon name="edit"/></button><button className="adm-icon-btn" title="Soft delete" onClick={()=>setDeleteTarget(product)}><Icon name="trash"/></button></div></td></tr>})}</tbody></table></div><div className="adm-pagination"><span>{data.meta?.total||rows.length} products · page {page}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>←</button><button disabled={page>=(data.meta?.totalPages||1)} onClick={()=>setPage(p=>p+1)}>→</button></div></div></>}</section>
 {editor!==undefined&&<ProductDrawer product={editor} createType={type} onClose={()=>setEditor(undefined)} onSaved={m=>flash(m)} onError={m=>flash(m,'error')}/>}<Confirm open={!!deleteTarget} title="Soft-delete product?" message={`“${deleteTarget?.title}” will disappear from the active catalogue. Existing orders remain intact.`} confirmLabel="Soft-delete" danger busy={busy} onClose={()=>setDeleteTarget(null)} onConfirm={remove}/>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</AdminShell>
}

export default function ProductsPage(){
 return <Suspense fallback={<div className="adm-app"><Skeleton rows={8}/></div>}><ProductsContent/></Suspense>;
}
