'use client';

import { FormEvent, useEffect, useState } from 'react';
import { adminFetch } from '@/lib/admin/client'; import { dateTime, money, Order, orderCustomer, orderEmail, orderPhone, orderTotal } from '@/lib/admin/types'; import { Icon } from './Icons'; import { Confirm, Skeleton, StatusBadge } from './UI';
const statuses=['PENDING','PROCESSING','PAID','SHIPPED','DELIVERED','CANCELLED','REFUNDED'];
export default function OrderDrawer({id,onClose,onSaved,onError}:{id:number;onClose:()=>void;onSaved:(m:string)=>void;onError:(m:string)=>void}){
 const [order,setOrder]=useState<Order|null>(null);const [busy,setBusy]=useState(false);const [pendingStatus,setPendingStatus]=useState<string|null>(null);const [draftStatus,setDraftStatus]=useState('');
 async function load(){try{const value=await adminFetch<Order>(`orders/${id}`);setOrder(value);setDraftStatus(value.status)}catch(e){onError(e instanceof Error?e.message:'Unable to load order.')}} useEffect(()=>{load()},[id]);
 async function saveFields(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!order)return;setBusy(true);const f=new FormData(e.currentTarget);try{await adminFetch(`orders/${id}`,{method:'PATCH',body:JSON.stringify({imei:f.get('imei')||undefined,customerType:f.get('customerType')||undefined,customerID:f.get('customerID')||undefined,deliveryOption:f.get('deliveryOption')||undefined})});onSaved('Order fields updated.');await load()}catch(e){onError(e instanceof Error?e.message:'Update failed.')}finally{setBusy(false)}}
 async function statusUpdate(){if(!order||!pendingStatus)return;setBusy(true);try{const form=document.getElementById('order-fields') as HTMLFormElement|null;const f=form?new FormData(form):new FormData();await adminFetch(`orders/${id}/status`,{method:'PUT',body:JSON.stringify({status:pendingStatus,trackingCode:f.get('trackingCode')||undefined,imei:f.get('imei')||undefined,customerType:f.get('customerType')||undefined,customerID:f.get('customerID')||undefined,deliveryOption:f.get('deliveryOption')||undefined})});setPendingStatus(null);onSaved(`Order status changed to ${draftStatus}.`);await load()}catch(e){onError(e instanceof Error?e.message:'Status update failed.')}finally{setBusy(false)}}
 const address=order?.shippingAddresses||order?.shippingAddress||order?.deliveryAddress||{};const payment=order?.payment||order?.paymentDetails||{};const items=order?.items||order?.orderItems||[];
 return <div className="adm-drawer-wrap"><button className="adm-modal-backdrop" onClick={onClose}/><section className="adm-drawer"><header className="adm-drawer-head"><div><h2>Order #{id}</h2><p>{order?dateTime(order.createdAt):'Loading order details…'}</p></div>{order&&<StatusBadge status={order.status}/>}<button className="adm-icon-btn" onClick={onClose}><Icon name="close"/></button></header><div className="adm-drawer-body">{!order?<Skeleton rows={7}/>:<>
 <section className="adm-section"><h3 className="adm-section-title">Customer & delivery</h3><div className="adm-kv"><div><small>Customer</small><strong>{orderCustomer(order)}</strong></div><div><small>Email</small><strong>{orderEmail(order)}</strong></div><div><small>Phone</small><strong>{orderPhone(order)}</strong></div><div><small>Address</small><strong>{[address.address1||address.address,address.address2,address.postcode||address.postalCode,address.city,address.state,address.country].filter(Boolean).join(', ')||'—'}</strong></div></div></section>
 <section className="adm-section"><h3 className="adm-section-title">Items</h3><div className="adm-items">{items.length?items.map((item:any,index:number)=><div className="adm-order-item" key={item.id||index}>{item.product?.images?.[0]?.url&&<img src={item.product.images[0].url} alt=""/>}<div><strong>{item.product?.title||item.productName||item.name||`Item ${index+1}`}</strong><small>{item.variant?.sku||item.sku||''} · Qty {item.quantity||1}</small></div><strong>{money(item.total||Number(item.price||0)*Number(item.quantity||1))}</strong></div>):<p className="adm-hint">No item data returned.</p>}</div></section>
 <section className="adm-section"><h3 className="adm-section-title">Payment</h3><div className="adm-kv"><div><small>Total</small><strong>{money(orderTotal(order))}</strong></div><div><small>Method</small><strong>{payment.method||order.paymentMethod?.name||order.paymentMethod||'—'}</strong></div><div><small>Payment status</small><strong>{payment.status||order.paymentStatus||order.status}</strong></div><div><small>Reference</small><strong>{payment.reference||payment.transactionId||order.paymentReference||'—'}</strong></div></div></section>
 <form id="order-fields" onSubmit={saveFields}><section className="adm-section"><h3 className="adm-section-title">Editable fulfilment fields</h3><div className="adm-form-grid"><label className="adm-field">IMEI<input name="imei" defaultValue={order.imei||''}/></label><label className="adm-field">Tracking code<input name="trackingCode" defaultValue={order.trackingCode||''}/><span className="adm-hint">Saved when status is updated.</span></label><label className="adm-field">Customer type<input name="customerType" defaultValue={order.customerType||''}/></label><label className="adm-field">Customer ID<input name="customerID" defaultValue={order.customerID||''}/></label><label className="adm-field">Delivery option<select name="deliveryOption" defaultValue={order.deliveryOption||''}><option value="">Not set</option><option value="DELIVER">Deliver</option><option value="PICKUP">Pickup</option></select></label><label className="adm-field">Order status<select value={draftStatus} onChange={e=>setDraftStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div></section></form>
 </>}</div><footer className="adm-drawer-foot"><button className="adm-button secondary" onClick={onClose}>Close</button>{order&&<><button className="adm-button secondary" form="order-fields" disabled={busy}>Save fields</button><button className="adm-button" disabled={busy||draftStatus===order.status} onClick={()=>setPendingStatus(draftStatus)}>Update status</button></>}</footer></section><Confirm open={!!pendingStatus} title="Change order status?" message={`Order #${id} will change from ${order?.status} to ${pendingStatus}. This may affect fulfilment and customer communication.`} confirmLabel={`Change to ${pendingStatus}`} danger={['CANCELLED','REFUNDED'].includes(pendingStatus||'')} busy={busy} onClose={()=>setPendingStatus(null)} onConfirm={statusUpdate}/></div>
}
