import { createHash } from 'node:crypto';
import { createPublicationJob, readPublicationJob, updatePublicationJob, type CataloguePublicationJob, type CataloguePublicationStepName } from './cataloguePublication.server';
import { normalizeProductEditorSpec, type ProductEditorSpec } from './productEditor';
import { fingerprintBundleProduct, normalizeBundleProduct } from './productBundleState';

type Row = Record<string, unknown>;
export type CataloguePreparedImageUpload = { key:string; name:string; contentType:string; order:number; body:unknown; sha256?:string; operationId?:string };
export type CatalogueVariantBinding = { valueKeys:string[]; variantId:number };
export type CatalogueImageBinding = { uploadKey:string; imageId:number; sha256:string; order:number };
export type CatalogueVariantUpdate = { id:number; sku:string; price:number; inventory:number };
export type CataloguePublishRequest = { catalogueId:string; spec:unknown; uploads:CataloguePreparedImageUpload[]; previousBundleProductId?:number|null; versionOrdinal:number };
export type CatalogueDraftPayload = { draft:true; draftMarker:string; operationId:string; attemptRevision:number; title:string; description:string; price:number; categories:string[]; tags:string[] };
export type CatalogueCompiledVariantsRequest = { optionName:'Catalogue Variant'; values:string[]; hidden:true; autoGenerateSku:true; defaultInventory:0; operationId:string };
export type CatalogueCompiledVariantsAttestation = { optionId:number; valueIdByCode:Record<string,number>; variantIdByCode:Record<string,number> };
export type CataloguePublishResult = { operationId:string; bundleProductId:number; bindings:CatalogueVariantBinding[]; imageBindings:CatalogueImageBinding[]; fingerprint:string };
export type CatalogueActivationState = { active?:boolean; operationId?:string; productId?:number; bundleProductId?:number; fingerprint?:string };
export type CatalogueRetirementState = { retired?:boolean; operationId?:string; previousProductId?:number; replacementProductId?:number };
export type CataloguePublishDependencies = {
  publicationDirectory?:string; draftMarker:string;
  createDraft(payload:CatalogueDraftPayload):Promise<unknown>; findDraftByOperation(operationId:string):Promise<unknown>;
  readProduct(productId:number):Promise<unknown>; readPublicationState(productId:number):Promise<unknown>;
  uploadImage(productId:number,upload:CataloguePreparedImageUpload):Promise<{imageId:number;sha256:string}>;
  createCompiledVariants(productId:number,request:CatalogueCompiledVariantsRequest):Promise<CatalogueCompiledVariantsAttestation>;
  batchUpdateVariants(productId:number,variants:CatalogueVariantUpdate[]):Promise<void>;
  publishProduct(productId:number,operationId:string):Promise<void>; restoreDraft(productId:number,operationId:string):Promise<void>;
  activateVersion(productId:number,bindings:CatalogueVariantBinding[],fingerprint:string,previousProductId:number|null,operationId:string):Promise<void>;
  readActivation(operationId:string,productId:number):Promise<CatalogueActivationState|null|undefined>; readActiveVersions():Promise<unknown>;
  retirePreviousVersion(previousProductId:number,replacementProductId:number,operationId:string):Promise<void>;
  readRetirement(previousProductId:number,replacementProductId:number):Promise<CatalogueRetirementState|null|undefined>;
  checkGlobalSkuAvailability(skus:string[],context:{excludeProductIds:number[]}):Promise<{available:boolean;collisions:unknown[];checkedSkus:string[];excludedProductIds:number[]}>;
};

export class CataloguePublishError extends Error { constructor(message:string,public status=422,public bundleProductId?:number){super(message);this.name='CataloguePublishError';} }
const object=(v:unknown):v is Row=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v);
const positive=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0;
const rows=(v:unknown)=>Array.isArray(v)?v.filter(object):[];
const numeric=(v:unknown)=>typeof v==='number'?v:typeof v==='string'&&v.trim()?Number(v):NaN;
const own=(v:Row,k:string)=>Object.prototype.hasOwnProperty.call(v,k);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:object(v)?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const hash=(v:Uint8Array|string)=>createHash('sha256').update(v).digest('hex');
const codeFor=(keys:string[])=>`CV-${hash(canonical(keys)).slice(0,24)}`;
const unwrap=(v:unknown):Row=>{const x=object(v)&&object(v.data)?v.data:v;if(!object(x))throw new CataloguePublishError('Bundle product readback is invalid.',502);return x;};
const idOf=(v:unknown)=>{const id=unwrap(v).id;if(!positive(id))throw new CataloguePublishError('Bundle did not return a valid draft product ID.',502);return id;};

const imageRows=(p:Row)=>rows(p.images), optionRows=(p:Row)=>rows(p.options), variantRows=(p:Row)=>rows(p.productVariants);
const digestOf=(r:Row)=>['sha256','digest','checksum','storageDigest'].map(k=>r[k]).find(x=>typeof x==='string') as string|undefined;
const publishQueues=new Map<string,Promise<void>>();

function enqueue<T>(key:string,action:()=>Promise<T>){const prior=publishQueues.get(key)??Promise.resolve();const run=prior.then(action);const tail=run.then(()=>undefined,()=>undefined);publishQueues.set(key,tail);return run.finally(()=>{if(publishQueues.get(key)===tail)publishQueues.delete(key);});}
function bytes(v:unknown){if(typeof Buffer!=='undefined'&&Buffer.isBuffer(v))return new Uint8Array(v);if(v instanceof Uint8Array)return new Uint8Array(v);if(v instanceof ArrayBuffer)return new Uint8Array(v.slice(0));return null;}
function validSignature(type:string,b:Uint8Array){if(type==='image/png')return b.length>=8&&[137,80,78,71,13,10,26,10].every((x,i)=>b[i]===x);if(type==='image/jpeg')return b.length>=3&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;return b.length>=12&&b[0]===82&&b[1]===73&&b[2]===70&&b[3]===70&&b[8]===87&&b[9]===69&&b[10]===66&&b[11]===80;}
function validateDependencies(d:CataloguePublishDependencies){const names=['createDraft','findDraftByOperation','readProduct','readPublicationState','uploadImage','createCompiledVariants','batchUpdateVariants','publishProduct','restoreDraft','activateVersion','readActivation','readActiveVersions','retirePreviousVersion','readRetirement','checkGlobalSkuAvailability'] as const;if(!d||typeof d.draftMarker!=='string'||!d.draftMarker.trim()||names.some(k=>typeof d[k]!=='function')||(d.publicationDirectory!==undefined&&typeof d.publicationDirectory!=='string'))throw new CataloguePublishError('Valid durable catalogue publication dependencies are required.',500);}
function validateUploads(v:unknown){
  if(!Array.isArray(v)||v.length>100)throw new CataloguePublishError('Image upload count must be at most 100.',400);
  const keys=new Set<string>(),orders=new Set<number>();let total=0;const allowed:Record<string,string[]>={'image/jpeg':['.jpg','.jpeg'],'image/png':['.png'],'image/webp':['.webp']};
  const out=v.map(raw=>{if(!object(raw)||typeof raw.key!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(raw.key)||keys.has(raw.key)||typeof raw.name!=='string'||raw.name!==raw.name.trim()||!raw.name||/[\\/\u0000-\u001f]/.test(raw.name)||typeof raw.contentType!=='string'||!allowed[raw.contentType]||!allowed[raw.contentType].some(x=>(raw.name as string).toLowerCase().endsWith(x))||!Number.isSafeInteger(raw.order)||numeric(raw.order)<0||orders.has(raw.order as number))throw new CataloguePublishError('Each image upload requires a unique key/order, safe matching JPEG/PNG/WebP name and content type.',400);const body=bytes(raw.body);if(!body||body.byteLength===0||body.byteLength>10*1024*1024)throw new CataloguePublishError('Image upload body type or item size is invalid.',400);if(!validSignature(raw.contentType,body))throw new CataloguePublishError('Image upload magic signature does not match its content type.',400);total+=body.byteLength;const sha=hash(body);if(raw.sha256!==undefined&&raw.sha256!==sha)throw new CataloguePublishError('Image upload digest does not match its body.',400);keys.add(raw.key);orders.add(raw.order as number);return {key:raw.key,name:raw.name,contentType:raw.contentType,order:raw.order as number,body,sha256:sha};}).sort((a,b)=>a.order-b.order);
  if(total>100*1024*1024)throw new CataloguePublishError('Total image upload size exceeds 100 MiB.',400);if(out.some((x,i)=>x.order!==i))throw new CataloguePublishError('Image upload order must be contiguous from zero.',400);return out;
}
function validateSpec(spec:ProductEditorSpec){const text=(v:unknown,max:number,required=false)=>typeof v==='string'&&v.length<=max&&(!required||v.trim().length>0);if(!text(spec.details.title,200,true)||!text(spec.details.description,10000)||spec.details.category!==undefined&&!text(spec.details.category,200,true)||!Number.isFinite(spec.details.price)||spec.details.price<0||spec.choices.length>2||spec.combinations.length>10000)throw new CataloguePublishError('Product text, price, choice or combination limits are invalid.',400);for(const c of spec.choices){if(!text(c.key,128,true)||!text(c.name,100,true)||c.values.length>100||c.values.some(v=>!text(v.key,128,true)||!text(v.label,100,true)))throw new CataloguePublishError('Choice/value counts or text lengths are invalid.',400);}for(const c of spec.combinations)if(c.sku!==undefined&&!text(c.sku,100,true)||!Number.isFinite(c.price)||c.price<0||!Number.isSafeInteger(c.inventory)||c.inventory<0)throw new CataloguePublishError('SKU, price or inventory limits are invalid.',400);const retired=new Set(spec.choices.flatMap(choice=>choice.values.filter(value=>value.retired).map(value=>value.key)));if(spec.details.price>0&&spec.combinations.some(combination=>combination.price===0&&combination.valueKeys.every(key=>!retired.has(key))))throw new CataloguePublishError('An active RM0 variant requires an explicit RM0 base price.',400);}
function matrix(spec:ProductEditorSpec){const choices=spec.choices.map(c=>({...c,values:c.values.filter(v=>!v.retired)}));if(choices.some(c=>!c.values.length))throw new CataloguePublishError('Every choice needs an active value.',400);const tuples:string[][]=[];const walk=(i:number,v:string[])=>i===choices.length?tuples.push(v):choices[i].values.forEach(x=>walk(i+1,[...v,x.key]));walk(0,[]);const activeKeysByChoice=choices.map(choice=>new Set(choice.values.map(value=>value.key))),activeCombinations=spec.combinations.filter(combination=>combination.valueKeys.length===activeKeysByChoice.length&&combination.valueKeys.every((key,index)=>activeKeysByChoice[index].has(key)));const map=new Map(activeCombinations.map(c=>[JSON.stringify(c.valueKeys),c]));if(map.size!==activeCombinations.length||map.size!==tuples.length||tuples.some(t=>!map.has(JSON.stringify(t))))throw new CataloguePublishError('A full unique active combination matrix is required.',400);return {tuples,combinations:tuples.map(t=>map.get(JSON.stringify(t))!)};}
function skuPlan(spec:ProductEditorSpec,m:ReturnType<typeof matrix>){const clean=(s:string)=>s.trim().toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-+|-+$/g,'');const labels=new Map(spec.choices.flatMap(c=>c.values.map(v=>[v.key,v.label] as const)));const combinations=m.combinations.map((c,i)=>clean(c.sku||[spec.details.title,...c.valueKeys.map(k=>labels.get(k)||k)].join('-'))||`PRODUCT-${i+1}`);if(combinations.some(x=>x.length>100)||new Set(combinations).size!==combinations.length)throw new CataloguePublishError('Duplicate normalized or oversized SKU values are not allowed.',400);return combinations;}
function providerSkuPlan(canonicalSkus:string[],catalogueId:string,versionOrdinal:number){const suffix=`-TW${catalogueId.slice(0,8)}V${versionOrdinal}`,providerSkus=canonicalSkus.map(sku=>`${sku.slice(0,100-suffix.length)}${suffix}`);if(suffix.length>=100||new Set(providerSkus).size!==providerSkus.length)throw new CataloguePublishError('Provider SKU values are not uniquely representable within 100 characters.',400);return providerSkus;}
async function read(d:CataloguePublishDependencies,id:number,label:string){try{return unwrap(await d.readProduct(id));}catch(e){if(e instanceof CataloguePublishError)throw e;throw new CataloguePublishError(`Bundle ${label} readback failed.`,502,id);}}
const MIN_PROVIDER_TITLE_SUFFIX_LENGTH=` [TW-${'0'.repeat(8)}-a1]`.length;
const MAX_PROVIDER_TITLE_SUFFIX_LENGTH=` [TW-${'0'.repeat(8)}-a${Number.MAX_SAFE_INTEGER}]`.length;
function metadata(p:Row,s:ProductEditorSpec){const titleMatches=p.title===s.details.title||s.details.title.length===200&&typeof p.title==='string'&&p.title.length>=200-MAX_PROVIDER_TITLE_SUFFIX_LENGTH&&p.title.length<=200-MIN_PROVIDER_TITLE_SUFFIX_LENGTH&&s.details.title.startsWith(p.title);if(!titleMatches||p.description!==s.details.description||numeric(p.price)!==s.details.price)throw new CataloguePublishError('Bundle product metadata verification failed.',502,positive(p.id)?p.id:undefined);}
function verifyImages(p:Row,uploads:ReturnType<typeof validateUploads>,resolved:Record<string,number>){const images=imageRows(p),byId=new Map(images.map(x=>[x.id,x]));if(images.length!==uploads.length||Object.keys(resolved).length!==uploads.length)throw new CataloguePublishError('Bundle image count verification failed.',502);uploads.forEach(u=>{const id=resolved[u.key],x=byId.get(id);if(!x||x.uploadKey!==u.key||x.order!==u.order||x.contentType!==u.contentType||digestOf(x)!==u.sha256)throw new CataloguePublishError('Bundle image storage digest/ID/order/type verification failed.',502);});}
function exactMap(actual:unknown,expected:Record<string,number>){return object(actual)&&same(Object.keys(actual).sort(),Object.keys(expected).sort())&&Object.entries(expected).every(([k,v])=>actual[k]===v);}
function flatSnapshot(p:Row,codes:string[]){
  const options=optionRows(p);if(options.length!==1)throw new CataloguePublishError('Bundle flat option count must be exact.',502);const option=options[0],values=rows(option.values);if(!positive(option.id)||option.name!=='Catalogue Variant'||values.length!==codes.length)throw new CataloguePublishError('Bundle Catalogue Variant option structure/ID/code count must be exact.',502);
  const valueIdByCode:Record<string,number>={};for(const value of values){if(typeof value.value!=='string'||!codes.includes(value.value)||!positive(value.id)||valueIdByCode[value.value])throw new CataloguePublishError('Bundle compiled value code/ID attestation is ambiguous.',502);valueIdByCode[value.value]=value.id;}if(Object.keys(valueIdByCode).length!==codes.length)throw new CataloguePublishError('Bundle compiled value code set is not exact.',502);
  const variants=variantRows(p);if(variants.length!==codes.length)throw new CataloguePublishError('Bundle compiled variant count is not exact.',502);const variantIdByCode:Record<string,number>={};for(const variant of variants){if(!positive(variant.id))throw new CataloguePublishError('Bundle compiled variant ID attestation is invalid.',502);const selected=rows(variant.selectedOptions);if(selected.length!==1)throw new CataloguePublishError('Bundle compiled variant selected-option mapping is not exact.',502);const selection=selected[0],code=selection.value;if(selection.optionId!==option.id||typeof code!=='string'||valueIdByCode[code]!==selection.valueId||variantIdByCode[code])throw new CataloguePublishError('Bundle compiled variant option/value ID mapping attestation failed.',502);variantIdByCode[code]=variant.id;}if(Object.keys(variantIdByCode).length!==codes.length)throw new CataloguePublishError('Bundle compiled variant code set is not exact.',502);
  return {optionId:option.id,valueIdByCode,variantIdByCode};
}
function verifyVariants(p:Row,codes:string[],updates:CatalogueVariantUpdate[],expected:ReturnType<typeof flatSnapshot>){const snap=flatSnapshot(p,codes);if(snap.optionId!==expected.optionId||!exactMap(snap.valueIdByCode,expected.valueIdByCode)||!exactMap(snap.variantIdByCode,expected.variantIdByCode))throw new CataloguePublishError('Bundle option/value/variant IDs did not remain stable.',502);const byId=new Map(variantRows(p).map(x=>[x.id,x]));for(const u of updates){const x=byId.get(u.id);if(!x||x.sku!==u.sku||numeric(x.price)!==u.price||numeric(x.inventory)!==u.inventory)throw new CataloguePublishError('Bundle variant SKU/price/inventory verification failed.',502);}return snap;}
function publicationEvidence(raw:unknown,id:number){const p=unwrap(raw),explicit=p.published===true||p.isPublished===true;if(p.id!==id||!explicit||p.deleted===true||p.deletedAt!=null||p.status==='deleted'||own(p,'published')&&p.published!==true||own(p,'isPublished')&&p.isPublished!==true||own(p,'draft')&&p.draft!==false||own(p,'draftOperationId'))throw new CataloguePublishError('Bundle explicit positive published state verification failed.',502,id);return p;}
function activeRows(raw:unknown){if(Array.isArray(raw))return raw.filter(object);if(object(raw)&&Array.isArray(raw.data))return raw.data.filter(object);throw new CataloguePublishError('Catalogue active-list attestation is invalid.',502);}
function activationMatches(a:CatalogueActivationState|null|undefined,op:string,id:number,fp:string){return Boolean(a&&a.active===true&&a.operationId===op&&(a.productId??a.bundleProductId)===id&&(a.fingerprint===undefined||a.fingerprint===fp));}
function activeAttested(raw:unknown,op:string,id:number,fp:string){return activeRows(raw).some(a=>a.active===true&&a.operationId===op&&(a.productId??a.bundleProductId)===id&&(a.fingerprint===undefined||a.fingerprint===fp));}
function externalBindings(bindings:CatalogueVariantBinding[],tuples:Map<string,string[]>){return bindings.map(binding=>({valueKeys:[...(tuples.get(binding.valueKeys[0])??[])],variantId:binding.variantId}));}
function resultFrom(job:CataloguePublicationJob,uploads:ReturnType<typeof validateUploads>,tuples:Map<string,string[]>):CataloguePublishResult{return {operationId:job.operationId,bundleProductId:job.draftBundleProductId!,bindings:externalBindings(job.bindings,tuples),imageBindings:uploads.map(u=>({uploadKey:u.key,imageId:job.resolved.images[u.key],sha256:u.sha256!,order:u.order})),fingerprint:job.resultFingerprint64!};}
async function checkpoint(job:CataloguePublicationJob,d:CataloguePublishDependencies,mutate:(j:CataloguePublicationJob)=>void,step?:CataloguePublicationStepName){try{return await updatePublicationJob(job.operationId,job.revision,j=>{mutate(j);if(step)j.completedSteps.push({name:step,completedAt:j.updatedAt});return j;},d.publicationDirectory);}catch(e){throw new CataloguePublishError(`Catalogue publication checkpoint CAS failed: ${e instanceof Error?e.message:'invalid update'}`,409,job.draftBundleProductId??undefined);}}
function validateRuntime(job:CataloguePublicationJob,op:string,catalogueId:string,model:string,previous:number|null){if(job.operationId!==op||job.catalogueId!==catalogueId||job.modelFingerprint64!==model||job.previousBundleProductId!==previous)throw new CataloguePublishError('Catalogue publication checkpoint does not match this immutable request.',409,job.draftBundleProductId??undefined);}
async function knownInactive(d:CataloguePublishDependencies,op:string,id:number){const a=await d.readActivation(op,id),list=await d.readActiveVersions();return a?.active===false&&!activeRows(list).some(x=>(x.productId??x.bundleProductId)===id&&x.active!==false);}
async function restore(d:CataloguePublishDependencies,job:CataloguePublicationJob){const id=job.draftBundleProductId;if(!id)return;let inactive=false;try{inactive=await knownInactive(d,job.operationId,id);}catch{throw new CataloguePublishError('Activation state is uncertain; draft restoration is forbidden.',503,id);}if(!inactive)throw new CataloguePublishError('Activation state is uncertain or active; draft restoration is forbidden.',503,id);try{await d.restoreDraft(id,job.operationId);const p=unwrap(await d.readPublicationState(id));const list=await d.readActiveVersions();if(p.draftOperationId!==job.operationId||p.published!==false||own(p,'isPublished')&&p.isPublished!==false||own(p,'draft')&&p.draft!==true||activeRows(list).some(x=>(x.productId??x.bundleProductId)===id&&x.active!==false))throw new Error('restore attestation');}catch{throw new CataloguePublishError('Draft restoration readback did not prove marker, unpublished and inactive state.',503,id);}}
function preflightEvidence(raw:unknown,skus:string[],excluded:number[]){if(!object(raw)||typeof raw.available!=='boolean'||!Array.isArray(raw.collisions)||!Array.isArray(raw.checkedSkus)||!Array.isArray(raw.excludedProductIds)||!same(raw.checkedSkus,skus)||!same(raw.excludedProductIds,excluded))throw new CataloguePublishError('Global SKU availability evidence attestation failed.',503);if(raw.available!==true||raw.collisions.length!==0)throw new CataloguePublishError('Global SKU collision: all publication SKUs must be available.',409);}

async function runPublication(request:CataloguePublishRequest,d:CataloguePublishDependencies,spec:ProductEditorSpec,uploads:ReturnType<typeof validateUploads>,m:ReturnType<typeof matrix>,skus:string[],model:string,previous:number|null){
  const op=model,codes=m.tuples.map(codeFor),tupleByCode=new Map(codes.map((code,i)=>[code,m.tuples[i]]));
  let job:CataloguePublicationJob;try{job=await readPublicationJob(op,d.publicationDirectory)??await createPublicationJob({operationId:op,catalogueId:request.catalogueId,modelFingerprint64:model,previousBundleProductId:previous},d.publicationDirectory);}catch(e){try{job=(await readPublicationJob(op,d.publicationDirectory))!;if(!job)throw e;}catch{throw new CataloguePublishError('Catalogue publication checkpoint could not be loaded or created.',503);}}
  validateRuntime(job,op,request.catalogueId,model,previous);if(job.phase==='complete')return resultFrom(job,uploads,tupleByCode);
  const excluded=Array.from(new Set([previous,job.draftBundleProductId].filter(positive)));let availability:unknown;try{availability=await d.checkGlobalSkuAvailability(structuredClone(skus),{excludeProductIds:excluded});}catch{throw new CataloguePublishError('Global SKU availability preflight failed.',503);}preflightEvidence(availability,skus,excluded);
  let reconciledDraft:unknown=null;if(job.phase==='building'){try{reconciledDraft=await d.findDraftByOperation(op);}catch{throw new CataloguePublishError('Catalogue publication is quarantined: provider operation marker discovery is ambiguous or unavailable.',409,job.draftBundleProductId??undefined);}if(job.draftBundleProductId!==null&&(!reconciledDraft||idOf(reconciledDraft)!==job.draftBundleProductId))throw new CataloguePublishError('Catalogue publication is quarantined: the durable draft ID does not uniquely match its provider operation marker.',409,job.draftBundleProductId);}
  if(!job.draftBundleProductId){
    let created:unknown=reconciledDraft,mutationError=false;
    if(!created){
      job=await checkpoint(job,d,()=>{});
      try{created=await d.createDraft({draft:true,draftMarker:d.draftMarker,operationId:op,attemptRevision:job.revision,title:spec.details.title,description:spec.details.description,price:spec.details.price,categories:spec.details.category===undefined?[]:[spec.details.category],tags:[]});}
      catch{mutationError=true;created=await d.findDraftByOperation(op);}
    }
    if(!created)throw new CataloguePublishError('Bundle draft creation failed and could not be reconciled.',502);
    const createdId=idOf(created),p=await read(d,createdId,'draft creation');metadata(p,spec);
    if(p.draft!==true||p.published!==false||p.draftOperationId!==op)throw new CataloguePublishError('Bundle draft marker verification failed.',502,createdId);
    job=await checkpoint(job,d,j=>{j.draftBundleProductId=createdId;},'draft-created');
    if(mutationError)throw new CataloguePublishError('Bundle draft creation timed out after a reconciled commit.',503,createdId);
  }
  const id=job.draftBundleProductId!;
  if(job.phase==='building'){
    try{
      let current=await read(d,id,'building');metadata(current,spec);
      if(!job.completedSteps.some(x=>x.name==='images-resolved')){const resolved:Record<string,number>={...job.resolved.images};for(const u of uploads){let image=imageRows(current).find(x=>x.uploadKey===u.key),mutationError=false,attestation:{imageId:number;sha256:string}|undefined;if(!image||image.order!==u.order||image.contentType!==u.contentType||digestOf(image)!==u.sha256){try{attestation=await d.uploadImage(id,{...u,operationId:op});}catch{mutationError=true;}current=await read(d,id,`image ${u.key}`);image=imageRows(current).find(x=>x.uploadKey===u.key);}if(!image||!positive(image.id)||image.order!==u.order||image.contentType!==u.contentType||digestOf(image)!==u.sha256)throw new CataloguePublishError(`Image ${u.key} storage digest readback mismatch.`,502,id);if(attestation&&(!positive(attestation.imageId)||attestation.sha256!==u.sha256||image.id!==attestation.imageId))throw new CataloguePublishError(`Image ${u.key} callback attestation mismatch.`,502,id);resolved[u.key]=image.id;if(mutationError){job=await checkpoint(job,d,j=>{j.resolved.images=resolved;});throw new CataloguePublishError(`Image ${u.key} upload timed out after a reconciled commit.`,503,id);}}verifyImages(current,uploads,resolved);job=await checkpoint(job,d,j=>{j.resolved.images=resolved;},'images-resolved');}else verifyImages(current,uploads,job.resolved.images);
      current=await read(d,id,'compiled variants');let compileError=false,attestation:CatalogueCompiledVariantsAttestation|undefined;if(optionRows(current).length===0){try{attestation=await d.createCompiledVariants(id,{optionName:'Catalogue Variant',values:[...codes],hidden:true,autoGenerateSku:true,defaultInventory:0,operationId:op});}catch{compileError=true;}current=await read(d,id,'compiled variants');}const snap=flatSnapshot(current,codes);if(attestation&&(attestation.optionId!==snap.optionId||!exactMap(attestation.valueIdByCode,snap.valueIdByCode)||!exactMap(attestation.variantIdByCode,snap.variantIdByCode)))throw new CataloguePublishError('Compiled variant callback attestation mapping does not match authoritative IDs.',502,id);
      if(!job.completedSteps.some(x=>x.name==='options-resolved')){const bindings=codes.map(code=>({valueKeys:[code],variantId:snap.variantIdByCode[code]}));job=await checkpoint(job,d,j=>{j.resolved.options={'catalogue-variant':snap.optionId};j.resolved.values={...snap.valueIdByCode};j.resolved.variants=Object.fromEntries(codes.map((code,i)=>[`v:${i}`,snap.variantIdByCode[code]]));j.bindings=bindings;},'options-resolved');job=await checkpoint(job,d,()=>{},'variants-resolved');}if(compileError)throw new CataloguePublishError('Compiled variant creation timed out after a reconciled commit.',503,id);
      const updates=m.combinations.map((c,i)=>({id:snap.variantIdByCode[codes[i]],sku:skus[i],price:c.price,inventory:c.inventory}));
      if(!job.completedSteps.some(x=>x.name==='variants-normalized')){let batchError=false;try{await d.batchUpdateVariants(id,structuredClone(updates));}catch{batchError=true;}current=await read(d,id,'normalized variants');try{verifyVariants(current,codes,updates,snap);verifyImages(current,uploads,job.resolved.images);}catch(reason){if(batchError)throw new CataloguePublishError('Variant batch update failed and authoritative readback did not prove normalization.',503,id);throw reason;}job=await checkpoint(job,d,()=>{},'variants-normalized');if(batchError)throw new CataloguePublishError('Variant update timed out after a reconciled commit.',503,id);}else{verifyVariants(current,codes,updates,snap);verifyImages(current,uploads,job.resolved.images);}
      let publishError=false;try{await d.publishProduct(id,op);}catch{publishError=true;}const published=publicationEvidence(await d.readPublicationState(id),id);metadata(published,spec);verifyVariants(published,codes,updates,snap);verifyImages(published,uploads,job.resolved.images);job=await checkpoint(job,d,j=>{j.phase='bundle-published';},'bundle-published');if(publishError)throw new CataloguePublishError('Bundle publication timed out after a reconciled commit.',503,id);
    }catch(reason){if(job.phase==='building')await restore(d,job);throw reason;}
  }
  let published:Row;try{published=publicationEvidence(await d.readPublicationState(id),id);}catch{try{await d.publishProduct(id,op);published=publicationEvidence(await d.readPublicationState(id),id);}catch{throw new CataloguePublishError('Bundle publication evidence could not be restored before activation.',503,id);}}
  const snap=flatSnapshot(published,codes);if(snap.optionId!==job.resolved.options['catalogue-variant']||!exactMap(snap.valueIdByCode,job.resolved.values)||codes.some((code,i)=>snap.variantIdByCode[code]!==job.bindings[i]?.variantId))throw new CataloguePublishError('Bundle option/value/variant IDs did not remain stable on resume.',502,id);verifyImages(published,uploads,job.resolved.images);const fp=fingerprintBundleProduct(normalizeBundleProduct(published));
  if(job.phase==='activation-uncertain'){let activation:CatalogueActivationState|null|undefined,list:unknown;try{activation=await d.readActivation(op,id);list=await d.readActiveVersions();}catch{throw new CataloguePublishError('Catalogue activation remains uncertain; authoritative readback must be retried.',503,id);}if(activationMatches(activation,op,id,fp)&&activeAttested(list,op,id,fp))job=await checkpoint(job,d,j=>{j.phase='activated';},'activated');else if(activation?.active===false&&!activeAttested(list,op,id,fp)){await restore(d,job);throw new CataloguePublishError('Catalogue activation was authoritatively not committed; draft restored.',503,id);}else throw new CataloguePublishError('Catalogue activation remains uncertain; no activation replay was attempted.',503,id);}
  if(job.phase==='bundle-published'){let actionError=false;try{await d.activateVersion(id,externalBindings(job.bindings,tupleByCode),fp,previous,op);}catch{actionError=true;}let activation:CatalogueActivationState|null|undefined,list:unknown;try{activation=await d.readActivation(op,id);list=await d.readActiveVersions();}catch{job=await checkpoint(job,d,j=>{j.phase='activation-uncertain';});throw new CataloguePublishError('Catalogue activation is uncertain; authoritative readback must be retried.',503,id);}if(!activationMatches(activation,op,id,fp)||!activeAttested(list,op,id,fp)){if(activation?.active===false&&!activeAttested(list,op,id,fp)){await restore(d,job);throw new CataloguePublishError('Catalogue activation was authoritatively not committed; draft restored.',503,id);}job=await checkpoint(job,d,j=>{j.phase='activation-uncertain';});throw new CataloguePublishError('Catalogue activation active-list attestation failed.',503,id);}job=await checkpoint(job,d,j=>{j.phase='activated';},'activated');if(actionError)throw new CataloguePublishError('Catalogue activation timed out after a reconciled commit.',503,id);}
  if(job.phase==='activated'||job.phase==='retirement-uncertain'){let retirementError=false;if(previous!==null){if(previous===id)throw new CataloguePublishError('Previous and replacement Bundle product IDs must differ.',409,id);let state:CatalogueRetirementState|null|undefined;try{state=await d.readRetirement(previous,id);}catch{if(job.phase==='activated')job=await checkpoint(job,d,j=>{j.phase='retirement-uncertain';});throw new CataloguePublishError('Previous-version retirement readback is uncertain.',503,id);}const matches=()=>state?.retired===true&&state.previousProductId===previous&&state.replacementProductId===id&&(state.operationId===undefined||state.operationId===op);if(!matches()){try{await d.retirePreviousVersion(previous,id,op);}catch{retirementError=true;}try{state=await d.readRetirement(previous,id);}catch{if(job.phase==='activated')job=await checkpoint(job,d,j=>{j.phase='retirement-uncertain';});throw new CataloguePublishError('Previous-version retirement is uncertain.',503,id);}if(!matches()){if(job.phase==='activated')job=await checkpoint(job,d,j=>{j.phase='retirement-uncertain';});throw new CataloguePublishError('Previous-version retirement identity/readback failed.',503,id);}}}job=await checkpoint(job,d,j=>{j.phase='previous-retired';},'previous-retired');if(retirementError)throw new CataloguePublishError('Previous-version retirement timed out after a reconciled commit.',503,id);}
  if(job.phase==='previous-retired')job=await checkpoint(job,d,j=>{j.phase='complete';j.resultFingerprint64=fp;},'complete');
  return resultFrom(job,uploads,tupleByCode);
}

function preparePublication(request:CataloguePublishRequest){
  let spec:ProductEditorSpec;try{spec=normalizeProductEditorSpec(request?.spec);}catch{throw new CataloguePublishError('A normalized product editor spec is required.',400);}validateSpec(spec);
  if(typeof request.catalogueId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(request.catalogueId))throw new CataloguePublishError('A valid catalogue ID is required.',400);const previous=request.previousBundleProductId==null?null:request.previousBundleProductId;if(previous!==null&&!positive(previous))throw new CataloguePublishError('A valid previous Bundle product ID is required.',400);if(!positive(request.versionOrdinal))throw new CataloguePublishError('A positive safe Bundle version ordinal is required.',400);
  const uploads=validateUploads(request.uploads),m=matrix(spec),canonicalSkus=skuPlan(spec,m),skus=providerSkuPlan(canonicalSkus,request.catalogueId,request.versionOrdinal),model=hash(canonical({catalogueId:request.catalogueId,spec,previous,versionOrdinal:request.versionOrdinal,uploads:uploads.map(({key,name,contentType,order,sha256})=>({key,name,contentType,order,sha256}))}));return {spec,previous,uploads,m,skus,model};
}
export const cataloguePublicationOperationId=(request:CataloguePublishRequest)=>preparePublication(request).model;
export async function publishCatalogueProductVersion(request:CataloguePublishRequest,d:CataloguePublishDependencies):Promise<CataloguePublishResult>{
  validateDependencies(d);const {spec,previous,uploads,m,skus,model}=preparePublication(request);
  return enqueue(`${d.publicationDirectory??''}\0${model}`,()=>runPublication(request,d,spec,uploads,m,skus,model,previous));
}
